stages:
  # - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/template-chapter/template-topic/slides
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      template-chapter-template-topic: template-chapter-template-topic

docusaurus:
  plugin: docusaurus
  options:
    course_name: Hardware Software Interface
    math: true
    sidebar: js
    structure:
      - Introduction: chapters/landing-page/README.md
      - Lab 1 - Number Representation:
          - Binary and Hexadecimal:
              path: chapters/intro-computer-architecture/binary-hex/
              extra:
                - media/
              subsections:
                - Reading/: reading/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Conversions/: conversions/
                            - Rotations/: rotations/
                            - Binary Even and Hexadecimal Odd/: odd-even/
          - Pointers in C:
              path: chapters/memory-layout/c-pointers/
              extra:
                - media/
              subsections:
                - Reading/: reading/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Length and Equality with Bitwise Operations/: len-xor/
                            - Mirror/: mirror/
      - Lab 2 - Memory Operations. Introduction to GDB:
          - Memory Operations:
              path: chapters/memory-layout/memory-operations/
              extra:
                - media/
              subsections:
                - Reading/: reading/
                - Guides:
                    path: guides/
                    subsections:
                      - Array vs Pointer/: array_vs_pointer/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Iterating through an Integer Array/: iterate/
                            - Deleting the First Occurrence of a Pattern from a String/: delete_first/
                            - Pixels/: pixels/
                            - Find Maximum in Array/: find_max/
                            - Bonus - Pointers/: pointers/
          - Introduction to GDB:
              path: chapters/memory-layout/introduction-to-GDB/
              subsections:
                - Reading/: reading/
                - Guides:
                    path: guides/
                    subsections:
                      - GDB Tutorial - Debugging a Segfault/: segfault/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Data Inspection/: inspect/
      - Lab 4 - Toolchain. GOTO:
          - GOTO statements in C:
              path: chapters/intro-computer-architecture/c-goto-statements/
              subsections:
                - Reading/: reading/
                - Guides:
                    path: guides/
                    subsections:
                      - GOTO Warm-up/: goto-warm-up/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Algorithms Using GOTO/: goto-algs/
          - Toolchain for Reverse Engineering:
              path: chapters/memory-security/reverse-engineering/
              subsections:
                - Reading/: reading/
                - Guides:
                    path: guides/
                    subsections:
                      - Compiler Explorer Tutorial/: compiler-explorer-tutorial/
                      - Ghidra Tutorial/: ghidra-tutorial/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Old Hits/: old-hits/
      - Lab 5 - Introduction to Assembly Language:
          - Introduction:
              path: chapters/hardware-software-interface/introduction/
              subsections:
                - Reading/: reading/
          - x86 Architecture Family:
              path: chapters/hardware-software-interface/x86-architecture-family/
              extra:
                - media/
              subsections:
                - Reading/: reading/
                - Guides:
                    path: guides/
                    subsections:
                      - First look at assembly instructions/: instructions/
                      - Discovering Assembly/: discovering-assembly/
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Conditional Jumps/: conditional-jumps/
                            - Grumpy Jumps/: grumpy-jumps/
                            - Sets/: sets/
                            - Min/: min/
                            - Fibonacci/: fibonacci/
                            - Carry Flag - Overflow Flag/: cf-of/
      - Lab 6 - Registers and Memory Addressing:
            - Registers:
                path: chapters/hardware-software-interface/registers/
                extra:
                  - media/
                subsections:
                  - Reading/: reading/
                  - Guides:
                      path: guides/
                      subsections:
                        - Multiply and Divide/: multiply-divide/
                        - Floating Point Exception/: floating-point-exception/
                  - Drills:
                      path: drills/
                      subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                              - Divide/: div/
                              - Multiply/: mul/
                              - Sum of first N numbers squared/: sum-squared/
            - Memory Addressing:
                path: chapters/hardware-software-interface/memory-addressing/
                subsections:
                  - Reading/: reading/
                  - Guides:
                      path: guides/
                      subsections:
                        - Addressing Arrays/: addressing-arrays/
                        - Declarations/: declarations/
                        - Loop/: loop/
                  - Drills:
                      path: drills/
                      subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                              - Sum Elements of Array/: sum-array/
                              - Count Elements of Array/: vec-count-if/
      - Lab 7 - Structures, vectors and strings:
            - Structures:
                path: chapters/hardware-software-interface/structures/
                subsections:
                  - Reading/: reading/
                  - Guides:
                      path: guides/
                      subsections:
                        - Students/: students/
                  - Drills:
                      path: drills/
                      subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                              - Fibonacci Sum/: fibonacci/
                              - Print Structure/: print-structure/
                              - Getters and Setters/: getters-setters/
            - Arrays:
                path: chapters/hardware-software-interface/arrays/
                subsections:
                  - Reading/: reading/
                  - Guides:
                      path: guides/
                      subsections:
                        - Max/: max/
                  - Drills:
                      path: drills/
                      subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                              - Find Substring/: find-substring/
                              - Mul Arrays/: mul-arrays/
                              - Courses/: courses/
      - Lab 11 - Buffer Management. Buffer Overflow:
            - Introduction to Buffers:
                path: chapters/memory-security/buffers-intro/
                subsections:
                  - Reading/: reading/
                  - Drills:
                      path: drills/
                      subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                              - Data Buffer/: data-buffer/
                              - Stack Buffer/: stack-buffer/
                              - Read Using gets/: read-stdin-gets/
                              - Read Using fgets/: read-stdin-fgets/
            - Buffer Overflow Vulnerabilities:
                path: chapters/memory-security/overflow-vuln/
                subsections:
                  - Reading/: reading/
                  - Drills:
                      path: drills/
                      subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                              - Overflow in C/: overflow-in-c/
                              - Overwrite Return Address/: overwrite-ret-addr/
                              - Overflow for Binary File/: overflow-for-binary/
    # static_assets:
    #   - template-chapter-template-topic: /build/make_assets/chapters/template-chapter/template-topic/slides/_site
    config_meta:
      title: Hardware Software Interface
      url: http://localhost/
      baseUrl: /hardware-software-interface/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://curs.upb.ro
      OCW: https://ocw.cs.pub.ro/courses/pclp2
      Facebook: https://www.facebook.com/10c1a
    copyright_string: OpenEdu Team
